#https://docs.ansible.com/ansible/2.3/intro_windows.html
#Here’s an example of how to use the win_stat module to test for file existence. 
#Note that the data returned by the win_stat module is slightly different than what is provided by the Linux equivalent:
- name: test stat module
  hosts: win
  tasks:
    - name: test stat module on file
      win_stat: path="C:/Windows/win.ini"
      register: stat_file

    - debug: var=stat_file

    - name: check stat_file result
      assert:
          that:
             - "stat_file.stat.exists"
             - "not stat_file.stat.isdir"
             - "stat_file.stat.size > 0"
             - "stat_file.stat.md5"