#https://docs.ansible.com/ansible/latest/user_guide/windows_usage.html
- name: Ensure 7-Zip is installed via Chocolatey
  hosts: win
  tasks:
      # Install/uninstall with chocolatey
      - name: Ensure 7-Zip is installed via Chocolatey
        win_chocolatey:
            name: 7zip
            state: present